version: '2'
services:
    unirestprueba-app:
        image: unirestprueba
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://unirestprueba-mysql:3306/unirestprueba?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    unirestprueba-mysql:
        extends:
            file: mysql.yml
            service: unirestprueba-mysql
